export const STORAGE_KEYS = {
  JOURNAL: '@whatTodo:journal',
  DIARY: '@whatTodo:diary',
  TASKS: '@whatTodo:tasks',
  LEARN_PROGRESS: '@whatTodo:learn_progress',
  SRS: '@whatTodo:srs',
  SETTINGS: '@whatTodo:settings',
  REWARDS: '@whatTodo:rewards',
  GAME_THEMES: '@whatTodo:game_themes',
  THEME: '@whatTodo:theme',
  AUTO_BACKUP_SETTINGS: '@whatTodo:auto_backup_settings',
  LAST_BACKUP_TIME: '@whatTodo:last_backup_time',
  ONBOARDING_COMPLETED: '@whatTodo:onboarding_completed',
  COMMUNITY: '@whatTodo:community',
  AI: '@whatTodo:ai',
  SCENARIOS: '@whatTodo:scenarios',
  SKILLS: '@whatTodo:skills',
  SESSIONS: '@whatTodo:sessions',
  WRONG_ANSWERS: '@whatTodo:wrong_answers',
  REPORTS: '@whatTodo:reports',
  MOTIVATION_COOLDOWN: '@whatTodo:motivation_cooldown',
} as const;
